### ISSUE TITLE
[suggestion] Can it get the time since a user last logged in?

### ISSUE THREAD

**Issue by Agnes4m** [vrchatapi/vrchatapi-python#10]
For example, in the image below, I want to get the last login time of an offline friend.

I didn't find this method in the docs, I was hoping to have this feature.

![8fa357b223ba914e0afefda56bb70c45_720](https://github.com/vrchatapi/vrchatapi-python/assets/70925546/8efae942-7459-406f-a13e-d759a61a4df5)

If you already have this method and I can't find it, then I'm sorry.

**Comment by lyzcoote** [comment]
You can use the Property of `last_login` on the [UsersAPI](https://github.com/vrchatapi/vrchatapi-python/blob/main/docs/User.md#properties)

**Comment by Agnes4m** [comment]
thanks
