### ISSUE TITLE
Login not working with certain usernames

### ISSUE THREAD

**Issue by Luois45** [vrchatapi/vrchatapi-python#12]
The login wasn't working for my account named "München".

**Comment by ariesclark** [comment]
Can you provide a reproducible code sample?

**Comment by fantiachan** [comment]
Login is only possible using letters from a to z and numbers from 0 to 9.
Try logging in with your email address

**Comment by Rexios80** [comment]
The credentials probably aren't encoded properly

**Comment by ariesclark** [comment]
Yup, you'll need to Base64 encode both your username & password, the Python library doesn't currently do this.

**Comment by ariesclark** [comment]
https://discord.com/channels/418093857394262020/418512124529344523/1270163691811115124
