### ISSUE TITLE
instance_id fail client side validation

### ISSUE THREAD

**Issue by Taiko2k** [vrchatapi/vrchatapi-python#15]
I was attempting to use `.get_user()` but that failed with the following error:

```
(<class 'ValueError'>, ValueError('Invalid value for `instance_id`, must be a follow pattern or equal to `/(private|offline|(wrld|wld)_[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}:(\\d+)(~region\\(([\\w]+)\\))?(~([\\w]+)\\(usr_([\\w-]+)\\)((\\~canRequestInvite)?)(~region\\(([\\w].+)\\))?~nonce\\((.+)\\))?)/`'), <traceback object at 0x7ff339ff9300>)
```

The format of `instance_id` in this case was:  `00000~hidden(usr_abc12345-0000-0000-00000-000000000000)`

Disabling client side validation in the configuration works as a workaround.

**Comment by ariesclark** [comment]
Could you provide the version of the package you're using. This was fixed in a recent update iirc.

**Comment by Taiko2k** [comment]
Oh I was using 1.15.0, I forgot to upgrade, by bad.
