### ISSUE TITLE
Readme is not updated in time

### ISSUE THREAD

**Issue by Agnes4m** [vrchatapi/vrchatapi-python#9]
I see this link here,named [example.py](https://github.com/vrchatapi/vrchatapi-python/blob/main/example.py),but file error 404 is displayed.

I noticed that the readme hasn't been updated in 6 months, does that mean there are no sample files anymore?

**Comment by Katistic** [comment]
That file never existed, idk when it was put on the README
Its a good idea though so gonna keep this issue open until I make some
